/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-tertiary': '#3f2e00',
        'surface-tint': '#b5c4ff',
        'on-tertiary-fixed-variant': '#5b4300',
        'surface-bright': '#363a3e',
        'primary-fixed': '#dce1ff',
        'on-surface': '#e0e3e8',
        'on-error-container': '#ffdad6',
        'surface-container': '#1c2024',
        'error-container': '#93000a',
        'primary-fixed-dim': '#b5c4ff',
        'surface-container-low': '#181c20',
        'on-secondary-fixed': '#00210c',
        'on-surface-variant': '#c5c6d2',
        error: '#ffb4ab',
        'inverse-on-surface': '#2d3135',
        'secondary-container': '#06bb63',
        'on-tertiary-container': '#b78900',
        'on-background': '#e0e3e8',
        'on-secondary-fixed-variant': '#005228',
        'on-error': '#690005',
        'inverse-primary': '#475b9c',
        'on-primary': '#142c6a',
        'surface-variant': '#31353a',
        'surface-container-lowest': '#0b0f12',
        'primary-container': '#0a2463',
        background: '#141920',
        'tertiary-container': '#372700',
        'surface-dim': '#141920',
        outline: '#8f909b',
        'on-secondary': '#003919',
        'surface-container-highest': '#31353a',
        'surface-container-high': '#262a2f',
        'on-primary-container': '#7a8ed2',
        'secondary-fixed-dim': '#4ae183',
        'on-tertiary-fixed': '#261a00',
        'tertiary-fixed': '#ffdf9e',
        'outline-variant': '#444650',
        'tertiary-fixed-dim': '#fabd00',
        'secondary-fixed': '#6bfe9c',
        tertiary: '#fabd00',
        'on-primary-fixed-variant': '#2e4382',
        'on-secondary-container': '#00431f',
        surface: '#141920',
        'on-primary-fixed': '#00164d',
        'inverse-surface': '#e0e3e8',
        primary: '#b5c4ff',
        secondary: '#4ae183',
      },
      fontFamily: {
        instrumentSans: ['"Instrument Sans"', 'sans-serif'],
        instrumentSerif: ['"Instrument Serif"', 'serif'],
        headline: ['Epilogue', 'sans-serif'],
        body: ['Inter', 'sans-serif'],
        label: ['Inter', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
